In [25]:
from bs4 import BeautifulSoup as bs
import requests
import time
import pandas as pd

In [26]:
base_url = 'https://fbref.com/'
scores_url = 'https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'

scores = requests.get(scores_url)
soup = bs(scores.text)
next_season = soup.find("a", class_="next")
next_season_link = base_url + next_season["href"]

In [27]:
table = pd.read_html(next_season_link)

In [28]:
next_season_link_soup = bs(requests.get(next_season_link).text)
next_season_title = next_season_link_soup.find_all('div', class_='comps')

In [29]:
next_season_title = next_season_link_soup.find('div', class_='comps')
next_season_title1 = next_season_title.find('h1').text.strip('\t\r\n')

In [30]:
nxt_season = next_season_title1.split("-")[1].split(" ")[0]
# browser.quit()

In [31]:
upcoming_matches = table[0]
upcoming_matches = upcoming_matches[['Wk', 'Day', 'Date', 'Time', 'Home', 'Away', 'Venue']]

In [32]:
upcoming_matches= upcoming_matches.dropna()

In [33]:
upcoming_matches['season'] = nxt_season
upcoming_matches['mod1'] = ''
upcoming_matches['mod2'] = ''
upcoming_matches['mod3'] = ''
upcoming_matches['mod4'] = ''

In [34]:
upcoming_matches_df = upcoming_matches.iloc[1:]

In [35]:
upcoming_matches_df = upcoming_matches_df.reset_index(drop=True)

In [36]:
upcoming_matches_df

,Wk,Day,Date,Time,Home,Away,Venue,season,mod1,mod2,mod3,mod4
0,1.0,Sat,2022-08-06,12:30,Fulham,Liverpool,Craven Cottage,2023,,,,
1,1.0,Sat,2022-08-06,15:00,Tottenham,Southampton,Tottenham Hotspur Stadium,2023,,,,
2,1.0,Sat,2022-08-06,15:00,Newcastle Utd,Nott'ham Forest,St. James' Park,2023,,,,
3,1.0,Sat,2022-08-06,15:00,Leeds United,Wolves,Elland Road,2023,,,,
4,1.0,Sat,2022-08-06,15:00,Bournemouth,Aston Villa,Vitality Stadium,2023,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
374,38.0,Sun,2023-05-28,15:00,Everton,Bournemouth,Goodison Park,2023,,,,
375,38.0,Sun,2023-05-28,15:00,Leicester City,West Ham,King Power Stadium,2023,,,,
376,38.0,Sun,2023-05-28,15:00,Aston Villa,Brighton,Villa Park,2023,,,,
377,38.0,Sun,2023-05-28,15:00,Leeds United,Tottenham,Elland Road,2023,,,,
378,38.0,Sun,2023-05-28,15:00,Brentford,Manchester City,Brentford Community Stadium,2023,,,,

In [43]:
upcoming_matches_df['Wk'].drop_duplicates().tolist()

[1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0]