In [52]:
from splinter import Browser
from bs4 import BeautifulSoup as bs
import time
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

In [53]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

base_url = 'https://fbref.com/'

scores_url = 'https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'

browser.visit(scores_url)

time.sleep(1)

# Scrape page into Soup
html = browser.html
soup = bs(html, "html.parser")

====== WebDriver manager ======
Current google-chrome version is 103.0.5060
Get LATEST chromedriver version for 103.0.5060 google-chrome
Driver [C:\Users\hk_la\.wdm\drivers\chromedriver\win32\103.0.5060.134\chromedriver.exe] found in cache

In [54]:
# next_season_comps = soup.find("div", class_='comps')
next_season = soup.find("a", class_="next")
next_season_link = base_url + next_season["href"]
browser.quit()

https://fbref.com//en/comps/9/11566/schedule/2022-2023-Premier-League-Scores-and-Fixtures

In [55]:
table = pd.read_html(next_season_link)

[       Wk  Day        Date   Time            Home  xG  Score  xG.1  \
 0     1.0  Fri  2022-08-05  20:00  Crystal Palace NaN    NaN   NaN
 1     1.0  Sat  2022-08-06  12:30          Fulham NaN    NaN   NaN
 2     1.0  Sat  2022-08-06  15:00       Tottenham NaN    NaN   NaN
 3     1.0  Sat  2022-08-06  15:00   Newcastle Utd NaN    NaN   NaN
 4     1.0  Sat  2022-08-06  15:00    Leeds United NaN    NaN   NaN
 ..    ...  ...         ...    ...             ...  ..    ...   ...
 412  38.0  Sun  2023-05-28  15:00         Everton NaN    NaN   NaN
 413  38.0  Sun  2023-05-28  15:00  Leicester City NaN    NaN   NaN
 414  38.0  Sun  2023-05-28  15:00     Aston Villa NaN    NaN   NaN
 415  38.0  Sun  2023-05-28  15:00    Leeds United NaN    NaN   NaN
 416  38.0  Sun  2023-05-28  15:00       Brentford NaN    NaN   NaN

                 Away  Attendance                        Venue  Referee  \
 0            Arsenal         NaN                Selhurst Park      NaN
 1          Liverpool         NaN               Craven Cottage      NaN
 2        Southampton         NaN    Tottenham Hotspur Stadium      NaN
 3    Nott'ham Forest         NaN              St. James' Park      NaN
 4             Wolves         NaN                  Elland Road      NaN
 ..               ...         ...                          ...      ...
 412      Bournemouth         NaN                Goodison Park      NaN
 413         West Ham         NaN           King Power Stadium      NaN
 414         Brighton         NaN                   Villa Park      NaN
 415        Tottenham         NaN                  Elland Road      NaN
 416  Manchester City         NaN  Brentford Community Stadium      NaN

      Match Report  Notes
 0    Head-to-Head    NaN
 1    Head-to-Head    NaN
 2    Head-to-Head    NaN
 3    Head-to-Head    NaN
 4    Head-to-Head    NaN
 ..            ...    ...
 412  Head-to-Head    NaN
 413  Head-to-Head    NaN
 414  Head-to-Head    NaN
 415  Head-to-Head    NaN
 416  Head-to-Head    NaN

 [417 rows x 14 columns]]

In [60]:
upcoming_matches = table[0]
upcoming_matches = upcoming_matches[['Wk', 'Day', 'Date', 'Time', 'Home', 'Away', 'Venue']]

In [64]:
upcoming_matches

,Wk,Day,Date,Time,Home,Away,Venue
0,1.0,Fri,2022-08-05,20:00,Crystal Palace,Arsenal,Selhurst Park
1,1.0,Sat,2022-08-06,12:30,Fulham,Liverpool,Craven Cottage
2,1.0,Sat,2022-08-06,15:00,Tottenham,Southampton,Tottenham Hotspur Stadium
3,1.0,Sat,2022-08-06,15:00,Newcastle Utd,Nott'ham Forest,St. James' Park
4,1.0,Sat,2022-08-06,15:00,Leeds United,Wolves,Elland Road
...,...,...,...,...,...,...,...
412,38.0,Sun,2023-05-28,15:00,Everton,Bournemouth,Goodison Park
413,38.0,Sun,2023-05-28,15:00,Leicester City,West Ham,King Power Stadium
414,38.0,Sun,2023-05-28,15:00,Aston Villa,Brighton,Villa Park
415,38.0,Sun,2023-05-28,15:00,Leeds United,Tottenham,Elland Road
416,38.0,Sun,2023-05-28,15:00,Brentford,Manchester City,Brentford Community Stadium

In [66]:
upcoming_matches_df = upcoming_matches.iloc[1:]

In [67]:
upcoming_matches_df = upcoming_matches_df.reset_index(drop=True)

In [69]:
import numpy as np
upcoming_matches_table = []
for i in np.arange(len(upcoming_matches_df)):
    up_wk = upcoming_matches_df['Wk']
    up_day = upcoming_matches_df['Day']
    up_date = upcoming_matches_df['Date']
    up_time = upcoming_matches_df['Time']
    up_home = upcoming_matches_df['Home']
    up_away = upcoming_matches_df['Away']
    up_venue = upcoming_matches_df['Venue']
    upcoming_matches_table.append({'Wk': up_wk, 'Day': up_day, 'Date': up_date, 'Time': up_time, 'Home': up_home, 'Away': up_away, 'Venue': up_venue})
upcoming_matches_table

[{'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28
  414    2023-05-28
  415    2023-05-28
  Name: Date, Length: 416, dtype: object,
  'Time': 0      12:30
  1      15:00
  2      15:00
  3      15:00
  4      15:00
         ...
  411    15:00
  412    15:00
  413    15:00
  414    15:00
  415    15:00
  Name: Time, Length: 416, dtype: object,
  'Home': 0              Fulham
  1           Tottenham
  2       Newcastle Utd
  3        Leeds United
  4         Bournemouth
              ...
  411           Everton
  412    Leicester City
  413       Aston Villa
  414      Leeds United
  415         Brentford
  Name: Home, Length: 416, dtype: object,
  'Away': 0            Liverpool
  1          Southampton
  2      Nott'ham Forest
  3               Wolves
  4          Aston Villa
              ...
  411        Bournemouth
  412           West Ham
  413           Brighton
  414          Tottenham
  415    Manchester City
  Name: Away, Length: 416, dtype: object,
  'Venue': 0                   Craven Cottage
  1        Tottenham Hotspur Stadium
  2                  St. James' Park
  3                      Elland Road
  4                 Vitality Stadium
                    ...
  411                  Goodison Park
  412             King Power Stadium
  413                     Villa Park
  414                    Elland Road
  415    Brentford Community Stadium
  Name: Venue, Length: 416, dtype: object},
 {'Wk': 0       1.0
  1       1.0
  2       1.0
  3       1.0
  4       1.0
         ...
  411    38.0
  412    38.0
  413    38.0
  414    38.0
  415    38.0
  Name: Wk, Length: 416, dtype: float64,
  'Day': 0      Sat
  1      Sat
  2      Sat
  3      Sat
  4      Sat
        ...
  411    Sun
  412    Sun
  413    Sun
  414    Sun
  415    Sun
  Name: Day, Length: 416, dtype: object,
  'Date': 0      2022-08-06
  1      2022-08-06
  2      2022-08-06
  3      2022-08-06
  4      2022-08-06
            ...
  411    2023-05-28
  412    2023-05-28
  413    2023-05-28